spring:
  application:
    name: onlinevotingsystem
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/OVS}
    username: ${DB_NAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
      connection-timeout: 1000
